name: "Snyk Notify GH Action 2"

on:
  push:
    branches:
      # update to master branch
      - master
    pull_request:
      branches:
       - master

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Sha
        env:
          SHA: ${GITHUB_SHA}
        run: echo "$SHA"


