name: "CustTest"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
      - uses: actions/checkout@main
      # For Snyk Open Source you must first set up the development environment for your application's dependencies
      # For example for Node
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up Snyk CLI to check for security issues
        run: |
         npm install snyk -g
         npm install snyk-to-html -g
         snyk auth ${SNYK_TOKEN}
         
      - name: Open Source Monitor  
        run: snyk monitor -d --all-projects --detection-depth=10 --org=732931c6-cf4e-49d3-83e4-a494892be357 --target-reference="main"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Code Test  
        # run: snyk code test --sarif > snyk-code.sarif || true
        run: |
         snyk code test --all-projects --detection-depth=10 --org=${{ secrets.SNYK_ORG }} --json > static_results.json

        
    # Upload Results  
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: codeResults.sarif
        
      # Upload Results  
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: SCAresults.sarif
      
